### ISSUE TITLE
how to send key enter or ok using SDK webos, please help me.

### ISSUE THREAD

**Issue by hoangchungk53qx1** [msonnino/LgTvWebOSSwift#2]

**Comment by msonnino** [comment]
Hi!
At what stage did you get stuck?
Were you able to connect to the TV? Are you able to send other commands?

**Comment by hoangchungk53qx1** [comment]
I connected using WebOS SDK successfully, I want to send the command "ok" or "enter" but it's not working.
    func sendEnterKey() {
        service?.sendEnter(success: { result in
            print(">>> sendDelete success \(result)")
        }, failure: { result in
            print(">>> sendDelete fail \(result)")
        })
    }
==> result failure

**Comment by hoangchungk53qx1** [comment]
i connected using webos sdk successfully i want to send command "ok" or "enter" but it doesnt work but i send other commands like volume up and down works fine

**Comment by msonnino** [comment]
> service?.sendEnter(success: { result in


What's "sendEnter"? Show me the function

**Comment by hoangchungk53qx1** [comment]
![Screen Shot 2021-08-22 at 13 45 57](https://user-images.githubusercontent.com/52132635/130345389-660f2b83-63fa-4abc-ba56-b85b9c2e21d4.png)
function senEnter

**Comment by msonnino** [comment]
In order to send an enter key you need to call
`lg.sendKey(.enter)`
Where “lg” is an instance of lgTvWebOs. 
where do you call it?

**Comment by hoangchungk53qx1** [comment]
I tried but failed. Can you show me a demo? .

**Comment by hoangchungk53qx1** [comment]
var service: WebOSTVService? = nil 
  service?.sendKeyCode(<#T##keyCode: UInt##UInt#>, success: <#T##SuccessBlock!##SuccessBlock!##(Any?) -> Void#>, failure: <#T##FailureBlock!##FailureBlock!##(Error?) -> Void#>)
 no key enter , im tried but failed.

**Comment by hoc081098** [comment]
any solution?

**Comment by msonnino** [comment]
I'm gonna have to take a deeper look at the problem. Gonna take a few days since this week is really super busy.

**Comment by msonnino** [comment]
Are you able to send all commaned? Only "Enter" doesn't work?

**Comment by hoangchungk53qx1** [comment]
yes, I can send every command, except "enter"

**Comment by msonnino** [comment]
In the meantime, it would really help if you could upload your code. Because so far what you've shown me wasn't very useful in trying to debug this problem.

**Comment by lambui09** [comment]
> In the meantime, it would really help if you could upload your code. Because so far what you've shown me wasn't very useful in trying to debug this problem.

![image](https://user-images.githubusercontent.com/31691936/130814906-e01f5a39-5be0-48c4-9568-d66dd24f62ef.png)

I am also facing the same issue with the "Enter" button. I think it may be affected by the new version of the TV, have you tested it with the new TV?

**Comment by dhruvnilu** [comment]
Would you be willing to share the demo project code where the rest of the buttons are working, it would be a great help?

**Comment by hoc081098** [comment]
@hoangchungk53qx1 😂

**Comment by hoangchungk53qx1** [comment]
@hoc081098  cười ẻ :))

**Comment by hoc081098** [comment]
> @hoc081098  cười ẻ :))

Nice
