### ISSUE TITLE
License for your Repo? 

### ISSUE THREAD

**Issue by eric-s321** [msonnino/LgTvWebOSSwift#3]
Hello - I'm working on an iPhone app that will connect to a LG Smart TV and I was actually in the process of making of swift version of https://github.com/supersaiyanmode/PyWebOSTV when I realized you already did that! I didn't see a license attached to your project and wanted to check with you if it's ok for me to use this repo in my app/how to source your material.

Thank you,
Eric

**Comment by msonnino** [comment]
Hey,
There are still modifications to make cause it doesn't work as it's bundled right now, but you can go ahead and use the source code no problem 👍🏻 👍🏻

**Comment by eric-s321** [comment]
That's no problem I'll probably have to tweak a few things anyhow but this saves me a lot of the leg work. Thank you!

**Comment by eric-s321** [comment]
Hi - was just wondering if when you were trying to connect to an LG TV using this method you ever ran into a problem where the simulator (and actual iphone) would connect to the TV and disconnect very rapidly (less than a second). The disconnect occurs before the popup on the TV displays and gives this generic error:

Disconnected: code=1008, reason=invalid origin

I tried the https://github.com/supersaiyanmode/PyWebOSTV version from my computer and it connects with no issues so I'm wondering if this is something iOS specific

**Comment by msonnino** [comment]
Can't remember having this problem.
But I also never tried a simulator. Only used a real TV.

**Comment by eric-s321** [comment]
Oh I meant the iphone simulator from xcode to a real tv. not a tv simulator. Same thing happens going from a real iphone to real tv though so probably not related
